-- OT1_schema.sql
-- Student ID: 
-- Student Name:


set echo on;

CREATE
    TABLE COUNTRY
    (
        COUNTRY_IOC_CODE CHAR (3) NOT NULL ,
        COUNTRY_IOC_NAME VARCHAR2 (50) NOT NULL,
        CONSTRAINT COUNTRY_PK PRIMARY KEY ( COUNTRY_IOC_CODE )
    ) ;
    
    
  


CREATE
    TABLE DRIVER_AUDIT
    (
        AUDIT_NO       NUMBER (8) NOT NULL ,
        DRIVER_ID      NUMBER (6) NOT NULL ,
        AUDIT_ORA_USER VARCHAR2 (30) NOT NULL ,
        AUDIT_DATETIME DATE NOT NULL,
        CONSTRAINT DRIVER_AUDIT_PK PRIMARY KEY ( AUDIT_NO )
    ) ;



CREATE
    TABLE DRIVER_AVAILABILITY
    (
        DRIVER_AVAIL_CODE CHAR (1) NOT NULL ,
        DRIVER_AVAIL_DESC VARCHAR2 (20) NOT NULL ,
        CONSTRAINT DRIVER_AVAILABILITY_PK PRIMARY KEY ( DRIVER_AVAIL_CODE )
    ) ;


CREATE
    TABLE FEATURE
    (
        FEATURE_ID   CHAR (2) NOT NULL ,
        FEATURE_DESC VARCHAR2 (50) NOT NULL,
        CONSTRAINT FEATURE_PK PRIMARY KEY ( FEATURE_ID )

    ) ;




CREATE
    TABLE IOC_ROLE
    (
        IOC_ROLE_CODE CHAR (2) NOT NULL ,
        IOC_ROLE_DESC VARCHAR2 (50) NOT NULL, 
        CONSTRAINT IOC_ROLE_PK PRIMARY KEY ( IOC_ROLE_CODE )

    ) ;


CREATE
    TABLE LANGUAGE
    (
        LANG_ISO_CODE CHAR (2) NOT NULL ,
        LANG_NAME     VARCHAR2 (50) NOT NULL, 
        CONSTRAINT LANGUAGE_PK PRIMARY KEY ( LANG_ISO_CODE )
    ) ;


CREATE
    TABLE LOCATION
    (
        LOCATION_ID     NUMBER (6) NOT NULL ,
        LOCATION_NAME   VARCHAR2 (40) ,
        LOCATION_STREET VARCHAR2 (50) NOT NULL ,
        LOCATION_TOWN   VARCHAR2 (30) NOT NULL ,
        LOCTYPE_ID      NUMBER (3) NOT NULL, 
        CONSTRAINT LOCATION_PK PRIMARY KEY ( LOCATION_ID )
    ) ;




CREATE
    TABLE LOCATION_TYPE
    (
        LOCTYPE_ID   NUMBER (3) NOT NULL ,
        LOCTYPE_DESC VARCHAR2 (50) NOT NULL, 
        CONSTRAINT LOCATION_TYPE_PK PRIMARY KEY (LOCTYPE_ID )
    ) ;


CREATE
    TABLE MAINT_REP
    (
        MR_NO       NUMBER (6) NOT NULL ,
        MR_DATE     DATE NOT NULL ,
        MR_ODOMETER NUMBER (6) NOT NULL ,
        MR_COST     NUMBER (7,2) NOT NULL ,
        MR_DETAILS  VARCHAR2 (250) NOT NULL ,
        VEH_VIN     CHAR (17) NOT NULL, 
        CONSTRAINT MAINT_REP_PK PRIMARY KEY ( MR_NO )
    ) ;


CREATE
    TABLE OFFICIAL
    (
        OFF_OLYMPIC_ID   CHAR (8) NOT NULL ,
        OFF_GIVENNAME    VARCHAR2 (50) NOT NULL ,
        OFF_FAMILYNAME   VARCHAR2 (50) NOT NULL ,
        IOC_ROLE_CODE    CHAR (2) NOT NULL ,
        COUNTRY_IOC_CODE CHAR (3) NOT NULL ,
        LANG_ISO_CODE    CHAR (2) NOT NULL, 
        CONSTRAINT OFFICIAL_PK PRIMARY KEY ( OFF_OLYMPIC_ID )
    ) ;



CREATE
    TABLE TRAINING
    (
        TRAINING_CODE CHAR (5) NOT NULL ,
        TRAINING_NAME VARCHAR2 (80) NOT NULL, 
        CONSTRAINT TRAINING_PK PRIMARY KEY ( TRAINING_CODE )
    ) ;





CREATE
    TABLE VEHICLE
    (
        VEH_VIN            CHAR (17) NOT NULL ,
        VEH_REGONUMBER     CHAR (7) NOT NULL ,
        VEH_MAKE           VARCHAR2 (40) NOT NULL ,
        VEH_MODEL          VARCHAR2 (40) NOT NULL ,
        VEH_COLOUR         VARCHAR2 (20) NOT NULL ,
        VEH_ODOMETER       NUMBER (6) NOT NULL ,
        VEH_SEATSAVAILABLE NUMBER (2) NOT NULL ,
        VEH_AVAIL_CODE     CHAR (1) NOT NULL, 
        CONSTRAINT VEHICLE_PK PRIMARY KEY ( VEH_VIN )
    ) ;


CREATE
    TABLE VEHICLE_FEATURE
    (
        VEH_VIN    CHAR (17) NOT NULL ,
        FEATURE_ID CHAR (2) NOT NULL, 
        CONSTRAINT VEHICLE_FEATURE_PK PRIMARY KEY (VEH_VIN, FEATURE_ID )
    );


CREATE
    TABLE VEH_AVAILABILITY
    (
        VEH_AVAIL_CODE CHAR (1) NOT NULL ,
        VEH_AVAIL_DESC VARCHAR2 (20) NOT NULL, 
        CONSTRAINT VEH_AVAILABILITY_PK PRIMARY KEY (VEH_AVAIL_CODE )
    ) ;




rem 1
ALTER TABLE VEHICLE ADD CONSTRAINT AVAILABILITY_VEHICLE_FK FOREIGN KEY (
VEH_AVAIL_CODE ) REFERENCES VEH_AVAILABILITY ( VEH_AVAIL_CODE ) ;

rem 2
ALTER TABLE OFFICIAL ADD CONSTRAINT COUNTRY_OFFICIAL_FK FOREIGN KEY (
COUNTRY_IOC_CODE ) REFERENCES COUNTRY ( COUNTRY_IOC_CODE ) ;



rem 3
ALTER TABLE VEHICLE_FEATURE ADD CONSTRAINT FEATURE_VEHICLE_FEATURE_FK FOREIGN
KEY ( FEATURE_ID ) REFERENCES FEATURE ( FEATURE_ID ) ;

rem 4
ALTER TABLE OFFICIAL ADD CONSTRAINT IOC_ROLE_OFFICIAL_FK FOREIGN KEY (
IOC_ROLE_CODE ) REFERENCES IOC_ROLE ( IOC_ROLE_CODE ) ;




rem 5
ALTER TABLE OFFICIAL ADD CONSTRAINT LANGUAGE_OFFICIAL_FK FOREIGN KEY (
LANG_ISO_CODE ) REFERENCES LANGUAGE ( LANG_ISO_CODE ) ;



rem 6
ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_TYPE_LOCATION_FK FOREIGN KEY (
LOCTYPE_ID ) REFERENCES LOCATION_TYPE ( LOCTYPE_ID ) ;



rem 7
ALTER TABLE MAINT_REP ADD CONSTRAINT VEHICLE_MAINT_REP_FK FOREIGN KEY ( VEH_VIN
) REFERENCES VEHICLE ( VEH_VIN ) ;


rem 8
ALTER TABLE VEHICLE_FEATURE ADD CONSTRAINT VEHICLE_VEHICLE_FEATURE_FK FOREIGN
KEY ( VEH_VIN ) REFERENCES VEHICLE ( VEH_VIN );







-- ========== ADD THE MISSING TABLE AND CONSTRAINT DEFINITIONS BELOW =======================


set echo off;


rem new add DRIVER_LANGUAGE
CREATE 
    TABLE DRIVER_LANGUAGE
    (
        DRIVER_ID     NUMBER (4) NOT NULL,
        LANG_ISO_CODE CHAR (2) NOT NULL,
        CONSTRAINT DRIVER_LANGUAGE_PK PRIMARY KEY (DRIVER_ID, LANG_ISO_CODE)
    );




rem new add TABLE DRIVER
CREATE
    TABLE DRIVER
    (
        DRIVER_ID              NUMBER (4)  NOT NULL,
        DRIVER_GIVENNAME       VARCHAR (50),
        DRIVER_FAMILYNAME      VARCHAR (50) NOT NULL,
        DRIVER_LICENCE_NO      CHAR (18)  NOT NULL,
        DRIVER_CLEARANCE_LEVEL CHAR (1)  NOT NULL,
        DRIVER_MODSCOMP        NUMBER (2)  NOT NULL,
        DRIVER_AVAIL_CODE      CHAR (1)  NOT NULL,
        CONSTRAINT DRIVER_PK PRIMARY KEY (DRIVER_ID)
    );
    
    
    
rem add new TABLE DRIVER_TRAINING;
CREATE
    TABLE DRIVER_TRAINING
    (
      DRIVER_ID     NUMBER (4) NOT NULL,
      TRAINING_CODE CHAR (5)  NOT NULL,
      DT_DATE_COMPLETED DATE  NOT NULL,
      CONSTRAINT  DRIVER_TRAINIG_PK PRIMARY KEY ( DRIVER_ID, TRAINING_CODE,
      DT_DATE_COMPLETED)
    );

    

CREATE
    TABLE TRIP
    (
        TRIP_ID  NUMBER(6)  NOT NULL,
        TRIP_START  DATE  NOT NULL,
        TRIP_END    DATE  NOT NULL,
        TRIP_START_ACTUAL DATE,
        TRIP_END_ACTUAL DATE,
        TRIP_START_KM NUMBER (6),
        TRIP_END_KM NUMBER (6),
        TRIP_PASSENGERS NUMBER (2) NOT NULL,
        VEH_VIN CHAR (17) NOT NULL,
        LOCATION_ID_FROM  NUMBER (6)  NOT NULL,
        LOCATION_ID_TO    NUMBER (6)  NOT NULL,
        OFF_OLYMPIC_ID    CHAR (8)  NOT NULL,
        DRIVER_ID   NUMBER (4)  NOT NULL,
        CONSTRAINT TRIP_PK  PRIMARY KEY (TRIP_ID)
    );



rem 9
ALTER TABLE DRIVER_LANGUAGE ADD CONSTRAINT DRIVER_ID_DRIVER_LANGUAGE_FK FOREIGN KEY ( 
DRIVER_ID ) REFERENCES DRIVER ( DRIVER_ID );

rem 10
ALTER TABLE DRIVER_LANGUAGE ADD CONSTRAINT LANGUAGE_DRIVER_LANGUAGE_FK FOREIGN KEY
( LANG_ISO_CODE ) REFERENCES LANGUAGE ( LANG_ISO_CODE );

rem 11
ALTER TABLE DRIVER ADD CONSTRAINT DRIVER_AVAILABILITY_DRIVER_FK FOREIGN KEY (
DRIVER_AVAIL_CODE ) REFERENCES DRIVER_AVAILABILITY ( DRIVER_AVAIL_CODE );

rem 12
ALTER TABLE DRIVER_TRAINING ADD CONSTRAINT TRAINING_DRIVER_TRAINING_FK FOREIGN KEY
(TRAINING_CODE) REFERENCES TRAINING (TRAINING_CODE);

rem 13
ALTER TABLE DRIVER_TRAINING ADD CONSTRAINT DRIVER_DRVIER_TRAINING_FK FOREIGN KEY 
( DRIVER_ID) REFERENCES DRIVER ( DRIVER_ID );




rem 14
ALTER TABLE TRIP ADD CONSTRAINT VEHICLE_TRIP_FK  FOREIGN KEY (VEH_VIN) 
REFERENCES VEHICLE ( VEH_VIN );

rem 15
ALTER TABLE TRIP ADD CONSTRAINT LOCATION__TRIP_FROM_FK FOREIGN KEY
(LOCATION_ID_FROM) REFERENCES LOCATION (LOCATION_ID);

rem 16
ALTER TABLE TRIP ADD CONSTRAINT LOCATION_TRIP_TO_FK FOREIGN KEY
(LOCATION_ID_TO)  REFERENCES LOCATION (LOCATION_ID);

rem 17
ALTER TABLE TRIP ADD CONSTRAINT DRIVER_TRIP_FK FOREIGN KEY
(DRIVER_ID) REFERENCES DRIVER (DRIVER_ID);

rem 18
ALTER TABLE TRIP ADD CONSTRAINT OFFICIAL_TRIP_FK FOREIGN KEY
(OFF_OLYMPIC_ID) REFERENCES OFFICIAL (OFF_OLYMPIC_ID);
