-- OT2_drop.sql
-- Student ID: 
-- Student Name:

set echo on;
-- Write your code below

rem 1
ALTER TABLE VEHICLE DROP CONSTRAINT AVAILABILITY_VEHICLE_FK;

rem 2
ALTER TABLE OFFICIAL DROP CONSTRAINT COUNTRY_OFFICIAL_FK;

rem 3
ALTER TABLE VEHICLE_FEATURE DROP CONSTRAINT FEATURE_VEHICLE_FEATURE_FK;

rem 4
ALTER TABLE OFFICIAL DROP CONSTRAINT IOC_ROLE_OFFICIAL_FK;

rem 5
ALTER TABLE OFFICIAL DROP CONSTRAINT LANGUAGE_OFFICIAL_FK;

rem 6
ALTER TABLE LOCATION DROP CONSTRAINT LOCATION_TYPE_LOCATION_FK;

rem 7
ALTER TABLE MAINT_REP DROP CONSTRAINT VEHICLE_MAINT_REP_FK;

rem 8
ALTER TABLE VEHICLE_FEATURE ADD CONSTRAINT VEHICLE_VEHICLE_FEATURE_FK;




DROP TABLE COUNTRY PURGE;
DROP TABLE DRIVER PURGE;
DROP TABLE DRIVER_AUDIT PURGE;
DROP TABLE DRIVER_AVAILABILITY PURGE;
DROP TABLE DRIVER_LANGUAGE PURGE;
DROP TABLE DRIVER_TRAINING PURGE;
DROP TABLE FEATURE PURGE;
DROP TABLE IOC_ROLE PURGE;
DROP TABLE LANGUAGE PURGE;
DROP TABLE LOCATION PURGE;
DROP TABLE LOCATION_TYPE PURGE;
DROP TABLE MAINT_REP PURGE;
DROP TABLE OFFICIAL PURGE;
DROP TABLE TRAINING PURGE;
DROP TABLE VEHICLE PURGE;
DROP TABLE VEHICLE_FEATURE PURGE;
DROP TABLE VEH_AVAILABILITY PURGE;
DROP TABLE TRIP PURGE;






set echo off;