-- OT2_drop.sql
-- Student ID: 
-- Student Name:

set echo on;
-- Write your code below

rem 1
ALTER TABLE VEHICLE DROP CONSTRAINT AVAILABILITY_VEHICLE_FK;

rem 2
ALTER TABLE OFFICIAL DROP CONSTRAINT COUNTRY_OFFICIAL_FK;

rem 3
ALTER TABLE VEHICLE_FEATURE DROP CONSTRAINT FEATURE_VEHICLE_FEATURE_FK;

rem 4
ALTER TABLE OFFICIAL DROP CONSTRAINT IOC_ROLE_OFFICIAL_FK;

rem 5
ALTER TABLE OFFICIAL DROP CONSTRAINT LANGUAGE_OFFICIAL_FK;

rem 6
ALTER TABLE LOCATION DROP CONSTRAINT LOCATION_TYPE_LOCATION_FK;

rem 7
ALTER TABLE MAINT_REP DROP CONSTRAINT VEHICLE_MAINT_REP_FK;

rem 8
ALTER TABLE VEHICLE_FEATURE DROP CONSTRAINT VEHICLE_VEHICLE_FEATURE_FK;

rem 9
ALTER TABLE DRIVER_LANGUAGE DROP CONSTRAINT DRIVER_ID_DRIVER_LANGUAGE_FK;

rem 10
ALTER TABLE DRIVER_LANGUAGE DROP CONSTRAINT LANGUAGE_DRIVER_LANGUAGE_FK;

rem 11
ALTER TABLE DRIVER DROP CONSTRAINT DRIVER_AVAILABILITY_DRIVER_FK;

rem 12
ALTER TABLE DRIVER_TRAINING DROP CONSTRAINT TRAINING_DRIVER_TRAINING_FK;

rem 13
ALTER TABLE DRIVER_TRAINING DROP CONSTRAINT DRIVER_DRVIER_TRAINING_FK;

rem 14
ALTER TABLE TRIP DROP CONSTRAINT VEHICLE_TRIP_FK;

rem 15
ALTER TABLE TRIP DROP CONSTRAINT LOCATION_TRIP_FROM_FK;

rem 16
ALTER TABLE TRIP DROP CONSTRAINT LOCATION_TRIP_TO_FK;

rem 17
ALTER TABLE TRIP DROP CONSTRAINT DRIVER_TRIP_FK;

rem 18
ALTER TABLE TRIP DROP CONSTRAINT OFFICIAL_TRIP_FK;




DROP TABLE COUNTRY PURGE;
DROP TABLE DRIVER PURGE;
DROP TABLE DRIVER_AUDIT PURGE;
DROP TABLE DRIVER_AVAILABILITY PURGE;
DROP TABLE DRIVER_LANGUAGE PURGE;
DROP TABLE DRIVER_TRAINING PURGE;
DROP TABLE FEATURE PURGE;
DROP TABLE IOC_ROLE PURGE;
DROP TABLE LANGUAGE PURGE;
DROP TABLE LOCATION PURGE;
DROP TABLE LOCATION_TYPE PURGE;
DROP TABLE MAINT_REP PURGE;
DROP TABLE OFFICIAL PURGE;
DROP TABLE TRAINING PURGE;
DROP TABLE VEHICLE PURGE;
DROP TABLE VEHICLE_FEATURE PURGE;
DROP TABLE VEH_AVAILABILITY PURGE;
DROP TABLE TRIP PURGE;

set echo off;